name: smoke-test

on:
  push:
  schedule:
    # First of the month at 7AM
    - cron: "0 11 1 * *"

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: OpenSSL version
      run: openssl version
    - name: Run scraper
      run: |
        scraper
    - name: Run poster
      run: |
        poster -m dry-run
      env:
        ELINK2_TOKEN_TEST: my-test-token
        ELINK2_TOKEN_PROD: my-prod-token
